### ISSUE TITLE
Erro fatal no cursosController

### ISSUE THREAD

**Issue by ArthurFleao** [IanTobar/Trabalho-Final-Adler#1]
Ao tentar acessar http://localhost/Trabalho-Final-Adler/public/curso/create

O Seguinte erro aparece.

FatalErrorException in CursosController.php line 21:
syntax error, unexpected '->' (T_OBJECT_OPERATOR)

**Comment by ruan113** [comment]
Falta da linha:

use redirect;

a qual é responsável para que se possa retornar para a view formulario após concluir uma inserção.
